/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   js-max-number-error.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

declare class JsMaxNumberError extends PolymerElement {

  /**
   * A number that is expected to be true.
   */
  expectedNumber: string|null|undefined;

  /**
   * Toggles the collapse element.
   */
  toggle(): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "js-max-number-error": JsMaxNumberError;
  }
}
